#!/bin/bash
# The script below fixes your code
# and add some helpers to ide's

./vendor/bin/php-cs-fixer fix
php artisan ide-helper:generate
php artisan ide-helper:eloquent
php artisan ide-helper:meta
php artisan ide-helper:models
php artisan ide-helper:actions
